MKSHELL="/bin/bash"

#target: OPTIONS: prereq
# option Q=QUIET does not show all messages

# obtain fasta files from ncbi using NCBI's EDirect tools
# efetch searchs and download .fasta, .fna and .faa files if a nucleotide db ID is given
# if efetch fails, a .fetcherror file should be created

# %.fasta.fetcherror:Q: %.fasta
# 	echo "[DEBUG] Looking for fetching errors in $prereq and saving them in $target"
# 	if [ $(cat $prereq | wc -l) -le 1 ]
# 	then
# 	echo "efetch could not find any DNA fasta sequence for $stem" > plasmid_$target && rm plasmid_"$stem".fasta
# 	elif [ $(cat "$stem"-prot.fna | wc -l) -le 1 ]
# 	then
# 	echo "efetch could not find any na sequence (for proteins) for $stem" > plasmid_"$stem"-prot.fna.fetcherror && rm plasmid_"$stem"-prot.fna
# 	fi
# 	if [ $(cat "$stem"-prot.faa | wc -l) -le 1 ]
# 	then
# 	echo "efetch could not find any aa sequence (for proteins) for $stem" > plasmid_"$stem"-prot.faa.fetcherror && rm plasmid_"$stem"-prot.faa
# 	fi


%.fasta:Q:
	echo "[DEBUG] fetching plasmid ID: $stem"
	efetch -db nuccore -id "$stem" -format fasta_cds_aa > plasmid_"$stem"-prot.faa
	efetch -db nuccore -id "$stem" -format fasta_cds_na > plasmid_"$stem"-prot.fna
	efetch -db nuccore -id "$stem" -format fasta > plasmid_"$target"
